services:
  ruok_whitespace:
    container_name: ruok_whitespace
    image: ruok_whitespace:latest
    build: ./app
    restart: always
    env_file:
      - ./.env
    ports:
      - 8505:8505
    volumes:
      - ./app:/app