[tool.ruff]
line-length = 120
fix = true

exclude = [
    "Dockerfile"
]


[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "ASYNC",
    "N",
    "UP",
    "YTT",
    "DTZ",
    "A",
    "B",
    "I"
]

[tool.ruff.lint.isort]
combine-as-imports = true
force-single-line = true